### PR TITLE
Lockout gui update

### LINKED ISSUE #379: Blocked screen icons background color on light mode should be white
screen where shown disabled until: 00:00 after entering wrong pin

### PR DESCRIPTION
**Pull request by mNizhurin**
closes #379

### CODE REVIEW

File: BankWallet/BankWallet/Modules/Pin/LockoutView.swift [hunk 1]
```diff
@@ -2,22 +2,32 @@ import UIKit
...
         super.init(frame: .zero)
         backgroundColor = AppTheme.controllerBackground
 
+        addSubview(iconBackgroundView)
+        iconBackgroundView.backgroundColor = PinTheme.lockoutIconBackground
+        iconBackgroundView.layer.cornerRadius = PinTheme.lockIconBackgroundSideSize / 2
+        iconBackgroundView.snp.makeConstraints { maker in
+            maker.centerX.equalToSuperview()
+            maker.centerY.equalToSuperview().multipliedBy(0.66)
+            maker.size.equalTo(CGSize(width: PinTheme.lockIconBackgroundSideSize, height: PinTheme.lockIconBackgroundSideSize))
```
Comment (ealymbaev) [inline BankWallet/BankWallet/Modules/Pin/LockoutView.swift]: Size can be set directly as a value. No need to create CGSize

File: BankWallet/BankWallet/Theme/PinTheme.swift [hunk 2]
```diff
@@ -9,10 +9,12 @@ class PinTheme {
     static let infoVerticalMargin: CGFloat = 16
 
     static let dismissAnimationDuration: Double = 0.3
```
Comment (ealymbaev) [inline BankWallet/BankWallet/Theme/PinTheme.swift]: Please reformat this file. Divide items by groups and sort them accordingly.
